/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlykitucxa;

import Process.HopDong;
import Process.Phong;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hieuuu
 */
public class DanhSachHopDongScreen extends javax.swing.JFrame {

    /**
     * Creates new form DanhSachHopDongScreen
     */
    private int demSua = 0;
    private int chonBang = 1; //1 la danh sach hop dong, 2 la danh sach phong con trong
    private final HopDong hd = new HopDong();
    private final Phong phong = new Phong();
    private boolean cothem = true;
    private final DefaultTableModel tableModel = new DefaultTableModel();

    void setEdi(boolean bl) {
        tf_maHD.setEditable(bl);
        tf_maSV.setEditable(bl);
        dp_ngayBatDau.setEditable(bl);
        dp_ngayKetThuc.setEditable(bl);
    }

    public void ShowData() throws SQLException {
        ResultSet rs = hd.ShowDanhSachHopDong();
        try {
            while (rs.next()) {
                String row[] = new String[4];
                row[0] = rs.getString("MaHD");
                row[1] = rs.getDate("NgayBatDau").toString();
                row[2] = rs.getDate("NgayKetThuc").toString();
                row[3] = rs.getString("MaSV");
                tableModel.addRow(row);

            }

        } catch (SQLException e) {

        }
    }

    public void ClearData() {
        int n = tableModel.getRowCount() - 1;
        for (int i = n; i >= 0; i--) {
            tableModel.removeRow(i);
        }
    }
//    private void setNull(){
//        this.tf_maLoai.setText("");
//        this.tf_tenLoai.setText("");
//        this.tf_maLoai.requestFocus();
//    }
//    private void setKhoa(boolean a){
//        this.tf_maLoai.setEnabled(!a);
//        this.tf_tenLoai.setEnabled(!a);
//    }
//    private void setButton(boolean a){
//        this.them.setEnabled(a);
//        this.xoa.setEnabled(a);
//        this.sua.setEnabled(a);
//        this.luu.setEnabled(!a);
//        this.kluu.setEnabled(!a);
//        this.thoat.setEnabled(a);
//    }

    public DanhSachHopDongScreen() throws SQLException {
        initComponents();

        setTitle("Quản lý kí túc xá");
        this.setLocationRelativeTo(null);
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        dp_ngayBatDau.setFormats(format);
        //  SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        dp_ngayKetThuc.setFormats(format);
        String[] colsName = {"Mã hợp đồng", "Thời gian bắt đầu", "Thời gian kết thúc", "Mã sinh viên"};
        tableModel.setColumnIdentifiers(colsName);
        jTable1.setModel(tableModel);
        ShowData();
        tf_maHD.setEditable(false);
        tf_maSV.setEditable(false);
        dp_ngayBatDau.setEditable(false);
        dp_ngayKetThuc.setEditable(false);
        setEdi(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try {
            jPanel1 =(javax.swing.JPanel)java.beans.Beans.instantiate(getClass().getClassLoader(), "quanlykitucxa.DanhSachHopDongScreen_jPanel1");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_maSV = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        dp_ngayBatDau = new org.jdesktop.swingx.JXDatePicker();
        jLabel7 = new javax.swing.JLabel();
        dp_ngayKetThuc = new org.jdesktop.swingx.JXDatePicker();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btn_hetHan = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        tf_maHD = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlykitucxa/images/logo_login.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 110, 1040, 150);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Quản lý hợp đồng thuê phòng ký túc xá");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 20, 1040, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlykitucxa/images/bg_big.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, -30, 1040, 220);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1036, 260);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Mã hợp đồng:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 290, 78, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Mã sinh viên:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(260, 290, 75, 17);
        getContentPane().add(tf_maSV);
        tf_maSV.setBounds(340, 280, 175, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 530, 1036, 140);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Ngày bắt đầu:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(520, 290, 78, 17);
        getContentPane().add(dp_ngayBatDau);
        dp_ngayBatDau.setBounds(600, 280, 164, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Ngày kết thúc:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(770, 290, 83, 17);
        getContentPane().add(dp_ngayKetThuc);
        dp_ngayKetThuc.setBounds(860, 280, 173, 30);

        jButton1.setText("Tìm kiếm theo mã sinh viên");
        getContentPane().add(jButton1);
        jButton1.setBounds(30, 400, 320, 39);

        jButton2.setText("Tìm kiếm theo ngày bắt đầu");
        getContentPane().add(jButton2);
        jButton2.setBounds(370, 400, 320, 39);

        jButton3.setText("Tìm kiếm theo ngày kết thúc");
        getContentPane().add(jButton3);
        jButton3.setBounds(710, 400, 290, 40);

        jButton4.setText("Thông tin chi tiết của sinh viên");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(710, 460, 290, 40);

        btn_hetHan.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btn_hetHan.setText("Hiển thị danh sách hợp đồng sắp hết hạn");
        btn_hetHan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hetHanActionPerformed(evt);
            }
        });
        getContentPane().add(btn_hetHan);
        btn_hetHan.setBounds(370, 460, 320, 40);

        jButton6.setText("Thêm hợp đồng");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(30, 340, 320, 39);

        btn_Sua.setText("Sửa hợp đồng");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Sua);
        btn_Sua.setBounds(370, 340, 320, 39);

        jButton8.setText("Xóa hợp đồng");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(710, 340, 290, 39);

        jButton9.setText("Quay lại");
        getContentPane().add(jButton9);
        jButton9.setBounds(480, 690, 73, 23);
        getContentPane().add(tf_maHD);
        tf_maHD.setBounds(90, 280, 157, 30);

        jButton10.setText("Danh sách yêu cầu của sinh viên");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10);
        jButton10.setBounds(30, 460, 320, 40);

        setBounds(0, 0, 1052, 778);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (chonBang == 1) {
            try {
                int row = this.jTable1.getSelectedRow();
                String maSV = (String) jTable1.getModel().getValueAt(row, 0);
                ResultSet rs = hd.ShowHopDongTheoMaHD(maSV);
                if (rs.next()) {
                    this.tf_maHD.setText(rs.getString("MaHD"));
                    this.tf_maSV.setText(rs.getString("MaSV"));
                    this.dp_ngayBatDau.setDate(rs.getDate("NgayBatDau"));
                    this.dp_ngayKetThuc.setDate(rs.getDate("NgayKetThuc"));
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        } else if (chonBang == 2) {
            int row = this.jTable1.getSelectedRow();
            String tenPhong = (String) jTable1.getModel().getValueAt(row, 1);
            int x = JOptionPane.showConfirmDialog(this, "Thêm sinh viên vào phòng " + tenPhong + "?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (x == 0) {
                toast t = new toast("Thêm thành công!", 600, 650);

                // call the method 
                t.showtoast();
            }
        }

    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            ThongTinSinhVienScreen a = new ThongTinSinhVienScreen(tf_maSV.getText());
            a.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(DanhSachHopDongScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String[] colsName = {"Mã sinh viên", "Tên sinh viên", "Hình thức yêu cầu"};
        tableModel.setColumnIdentifiers(colsName);
        ClearData();

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            // TODO add your handling code here:
            chonBang = 2;
            String[] colsName = {"Số phòng", "Tên phòng", "Loại phòng"};
            tableModel.setColumnIdentifiers(colsName);
            ClearData();
            ResultSet rs = phong.ShowPhongConTrongTheoLoaiPhong("CB");
            try {
                while (rs.next()) {
                    String row[] = new String[4];
                    row[0] = rs.getString("SoPhong");
                    row[1] = rs.getString("TenPhong");
                    row[2] = rs.getString("LoaiPhong");
                    tableModel.addRow(row);

                }

            } catch (SQLException e) {

            }
        } catch (SQLException ex) {
            Logger.getLogger(DanhSachHopDongScreen.class.getName()).log(Level.SEVERE, null, ex);

        }
        jTable1.setModel(tableModel);
       int x= JOptionPane.showConfirmDialog(this, "Đồng ý thêm hợp đồng?", "Thông báo", JOptionPane.YES_NO_OPTION);
       toast t = new toast("Thêm thành công!", 600, 650);

                // call the method 
               
                t.showtoast();
                //setEdi(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        demSua++;
        if (demSua % 2 == 1) {
            setEdi(true);
            btn_Sua.setText("Lưu");
        } else {
            int x = JOptionPane.showConfirmDialog(this, "Bạn đã chắc chắn sửa đúng thông tin?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (x == 0) {
                toast t = new toast("Sửa thành công!", 600, 650);

                // call the method 
                btn_Sua.setText("Sửa hợp đồng");
                t.showtoast();
                setEdi(false);

            }
        }
    }//GEN-LAST:event_btn_SuaActionPerformed
    private int demHetHan=0;
    private void btn_hetHanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hetHanActionPerformed
        // TODO add your handling code here:
        demHetHan++;
        if(demHetHan%2==1){
            btn_hetHan.setText("Gửi thông báo");
            
        }
        else {
            toast t = new toast("Gửi thành công!", 600, 650);

                // call the method
                btn_hetHan.setText("Hiển thị danh sách hợp đồng sắp hết hạn");
                t.showtoast();
                
        }
    }//GEN-LAST:event_btn_hetHanActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        int x= JOptionPane.showConfirmDialog(this, "Đồng ý xóa hợp đồng?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if(x==0){
            toast t = new toast("Xóa thành công!", 600, 650);

                // call the method 
               
                t.showtoast();
        }
       
                //setEdi(false);
                   
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DanhSachHopDongScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DanhSachHopDongScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DanhSachHopDongScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DanhSachHopDongScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DanhSachHopDongScreen().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(DanhSachHopDongScreen.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_hetHan;
    private org.jdesktop.swingx.JXDatePicker dp_ngayBatDau;
    private org.jdesktop.swingx.JXDatePicker dp_ngayKetThuc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tf_maHD;
    private javax.swing.JTextField tf_maSV;
    // End of variables declaration//GEN-END:variables
}
