/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlykitucxa;

import Process.HopDong;
import Process.Phong;
import Process.SinhVien;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author hieuuu
 */
public class SinhVienDangKyScreen extends javax.swing.JFrame {

    /**
     * Creates new form SinhVienDangKyScreen
     */
    private final SinhVien sv = new SinhVien();
    private final Phong ph = new Phong();

    public SinhVienDangKyScreen() {
        initComponents();
        setTitle("Quản lý kí túc xá");
        this.setLocationRelativeTo(null);
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        dp_ngaySinh.setFormats(format);
        /* tf_diaChiThuongTru.setText("1");
        tf_email.setText("1");
        tf_hoten.setText("1");
        tf_loaiPhong.setText("1");
        tf_maSinhVien.setText("1");
        tf_matKhau.setText("1");
        tf_ngaySinh.setText("1");
        tf_nhapLaiMatKhau.setText("1");
        tf_queQuan.setText("1");
        tf_soChungMinhThu.setText("1");
        tf_soDienThoai.setText("1");
        tf_taiKhoan.setText("1");*/
        ButtonGroup grGioiTinh = new ButtonGroup();
        grGioiTinh.add(rb_Nam);
        grGioiTinh.add(rb_Nu);
        ButtonGroup grPhong = new ButtonGroup();
        grPhong.add(rb_phongCoBan);
        grPhong.add(rb_phongCLC);
        grPhong.add(rb_phongTieuChuan);
        ButtonGroup grHocLuc = new ButtonGroup();
        grHocLuc.add(rb_kha);
        grHocLuc.add(rb_gioi);
        grHocLuc.add(rb_yeu);
        grHocLuc.add(rb_tb);
        ButtonGroup grHanhKiem = new ButtonGroup();
        grHanhKiem.add(rb_hkKha);
        grHanhKiem.add(rb_hkTB);
        grHanhKiem.add(rb_hkTot);
        grHanhKiem.add(rb_hkYeu);
        rb_hkKha.setSelected(true);
        rb_Nam.setSelected(true);
        rb_phongCoBan.setSelected(true);
        rb_kha.setSelected(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tf_hoten = new javax.swing.JTextField();
        tf_maSinhVien = new javax.swing.JTextField();
        tf_queQuan = new javax.swing.JTextField();
        tf_soChungMinhThu = new javax.swing.JTextField();
        tf_email = new javax.swing.JTextField();
        tf_soDienThoai = new javax.swing.JTextField();
        cb_camKet = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tf_taiKhoan = new javax.swing.JTextField();
        tf_matKhau = new javax.swing.JPasswordField();
        tf_nhapLaiMatKhau = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        rb_Nam = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        rb_Nu = new javax.swing.JRadioButton();
        dp_ngaySinh = new org.jdesktop.swingx.JXDatePicker();
        rb_phongCLC = new javax.swing.JRadioButton();
        rb_phongCoBan = new javax.swing.JRadioButton();
        rb_phongTieuChuan = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        rb_yeu = new javax.swing.JRadioButton();
        rb_tb = new javax.swing.JRadioButton();
        rb_kha = new javax.swing.JRadioButton();
        rb_gioi = new javax.swing.JRadioButton();
        jLabel19 = new javax.swing.JLabel();
        rb_hkYeu = new javax.swing.JRadioButton();
        rb_hkTB = new javax.swing.JRadioButton();
        rb_hkKha = new javax.swing.JRadioButton();
        rb_hkTot = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        tf_soThang = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("PHÒNG CÔNG TÁC SINH VIÊN");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("TRUNG TÂM PHỤC VỤ SINH VIÊN");

        jLabel3.setText("-------------------------------------------");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PHIẾU ĐĂNG KÝ Ở KÝ TÚC XÁ");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Số chứng minh thư:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("Loại phòng đăng ký:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Mã sinh viên:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Số điện thoại:");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Email:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("Ngày sinh:");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel15.setText("Họ tên:");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel16.setText("Quê quán:");

        tf_soChungMinhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_soChungMinhThuActionPerformed(evt);
            }
        });

        cb_camKet.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cb_camKet.setText("Tôi cam kết chấp hành nội quy Ký túc xá.");

        jButton1.setText("Nội quy ký túc xá");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Các loại phòng ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quanlykitucxa/images/logo_login_SMALL.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Tài khoản:");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Mật khẩu:");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel17.setText("Xác nhận lại mật khẩu:");

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton3.setText("Đăng ký");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton4.setText("Quay lại");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        rb_Nam.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rb_Nam.setText("Nam");
        rb_Nam.setActionCommand("");
        rb_Nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_NamActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setText("Giới tính:");

        rb_Nu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rb_Nu.setText("Nữ");
        rb_Nu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_NuActionPerformed(evt);
            }
        });

        rb_phongCLC.setText("Phòng chất lượng cao");

        rb_phongCoBan.setText("Phòng cơ bản");

        rb_phongTieuChuan.setText("Phòng tiêu chuẩn");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Học lực:");

        rb_yeu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rb_yeu.setText("Yếu");

        rb_tb.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rb_tb.setText("Trung bình");

        rb_kha.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rb_kha.setText("Khá");

        rb_gioi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rb_gioi.setText("Giỏi");

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel19.setText("Hạnh kiểm:");

        rb_hkYeu.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rb_hkYeu.setText("Yếu");

        rb_hkTB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rb_hkTB.setText("Trung bình");

        rb_hkKha.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rb_hkKha.setText("Khá");

        rb_hkTot.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        rb_hkTot.setText("Tốt");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel20.setText("Số tháng đăng ký ở: ");

        jLabel21.setText("( tháng )");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_taiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel9)
                    .addComponent(jLabel19)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_matKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tf_nhapLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel4)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_soThang, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cb_camKet, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_hoten))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_maSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dp_ngaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rb_Nam)
                                    .addGap(6, 6, 6)
                                    .addComponent(rb_Nu))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_queQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_soChungMinhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_phongCLC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rb_phongCoBan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rb_phongTieuChuan))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rb_yeu)
                                    .addComponent(rb_hkYeu))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(rb_hkTB)
                                        .addGap(17, 17, 17)
                                        .addComponent(rb_hkKha)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb_hkTot))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(rb_tb)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb_kha)
                                        .addGap(18, 18, 18)
                                        .addComponent(rb_gioi))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(tf_hoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_maSinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel18)
                    .addComponent(rb_Nam)
                    .addComponent(rb_Nu)
                    .addComponent(dp_ngaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(tf_queQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_soChungMinhThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_soDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rb_phongCLC)
                        .addComponent(rb_phongCoBan)
                        .addComponent(rb_phongTieuChuan)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tf_soThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_taiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_matKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(tf_nhapLaiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rb_yeu)
                    .addComponent(rb_tb)
                    .addComponent(rb_kha)
                    .addComponent(rb_gioi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(rb_hkYeu)
                    .addComponent(rb_hkTB)
                    .addComponent(rb_hkKha)
                    .addComponent(rb_hkTot))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cb_camKet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_soChungMinhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_soChungMinhThuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_soChungMinhThuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        NoiQuyKyTucXa nq = new NoiQuyKyTucXa();
        nq.setVisible(true);

        //JOptionPane.showMessageDialog(this, " Điều 1: HSSV có nguyện vọng ở nội trú phải làm đơn gửi  trung tâm Ký túc xá, hợp đồng thuê nhà ở và phải thực  hiện những cam kết ghi trong hợp đồng.  Điều 2: Giữ gìn an ninh, trật tự chung. Chấp hành nội quy giờ giấc học tập, sinh hoạt. Không tụ tập, tổ chức  bè phái, kích động, gây gổ, đánh nhau gây mất trật tự  trong Ký túc xá. Không ngồi, leo trèo, đi lại trên lan  can. Không vượt rào, trèo tường, ra khỏi ký túc xá.  Không thức khuya quá 23h30.  Điều 3: Không tự ý thay đổi chỗ ở, không tiếp khách  trong phòng. Bạn bè, người đến thăm tiếp đón tạo nơi  quy định, nghỉ lại qua đêm phải đăng ký, làm đơn bảo  lãnh đối với Trung tâm Ký túc xá.  Điều 4: Không leo trèo, hái hoa, bẻ cành, chặt phá cây,  ngồi chơi thêm thảm cỏ, hoa. Không đá bóng, đi, để xe  đạp, xe máy trong Ký túc xá. Không ngồi tự học, đi chơi  đôi nam, nữ nơi vắng vẻ trong đêm tối.  Điều 5: Không được uống rượu, bia trong Ký túc xá.  Không vận chuyển, tàng trữ, sử dụng và lôi kéo người  khác sử dụng các loại vũ khí, hung khí, chất cháy nổ,  các chất ma túy, tài liệu, băng đĩa có nội dung đồi  trụy, đánh bài, cờ bạc, mại dâm dưới bất kỳ hình thức  nào.  Điều 6: Có trách nhiệm giữ vệ sinh chung, thực hiện vệ  sinh hằng ngày, phòng ở sạch sẽ, gọn gàng, ngăn nắp. Đồ  dùng, tư trang cá nhân để đúng nơi quy định. Không viết, vẽ, dán giấy, tranh ảnh, đóng đinh lên tường, cửa. Giấy rác, đồ thải bỏ đúng nơi quy định.  Điều 7: Có trách nhiệm giữ gìn, bảo vệ tài sản cá nhân và tải sản trong khu nội trú. Không mang tài sản được  trang bị từ nơi này đến nơi khác. Nếu làm hư hỏng, mất  mát phải bồi thường theo quy định.  Điều 8: Chấp hành nghiêm chỉnh nội quy sử dụng cầu thang  máy, nhà ăn, quy định sử dụng điện, nước, internet.  Nghiêm cấm nấu ăn, tổ chức sinh nhật trong phòng ở với  bất kỳ hình thức nào.  Điều 9: Không có hành vi, tác phong ăn mặc thiếu văn hóa  gây ảnh hưởng tới môi trường sống. Ứng xử hòa nhã, lịch  sự, có văn hóa với bạn bè. Tôn trọng, lễ phép với Cán  bộ, Giáo viên, Công nhân viên trong Nhà trường.  Điều 10: Nếu vi phạm một trong những điều trên tùy theo  mức độ sẽ bị xử lý từ phê bình, khiển trách, cảnh cáo,  hủy hợp đồng thuê nhà ở nội trú, buộc thôi học, đề nghị  truy tố trước pháp luật.", "Nội quy ở ký túc xá", JOptionPane.PLAIN_MESSAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn quay lại?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (x == 0) {
            this.dispose();
            DangNhapScreen a = new DangNhapScreen();
            a.setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        String email = tf_email.getText();
        String hoTen = tf_hoten.getText();
        String maSV = tf_maSinhVien.getText();
        String matKhau = tf_matKhau.getText();
        int thangO = Integer.parseInt(tf_soThang.getText());
        int checkNgaySinh = 1;
        String ngaySinh = "";
        try {
            java.util.Date departDateD = dp_ngaySinh.getDate();
            SimpleDateFormat oDateFormat = new SimpleDateFormat("yyyy-MM-dd");
            SimpleDateFormat ngay = new SimpleDateFormat("dd");
            SimpleDateFormat thang = new SimpleDateFormat("MM");
            SimpleDateFormat nam = new SimpleDateFormat("yyyy");
            ngaySinh = oDateFormat.format(departDateD);
            Date date = new Date();
            int namm = Integer.parseInt(nam.format(date));
            int thangg = Integer.parseInt(thang.format(date));
            int ngayy = Integer.parseInt(ngay.format(date));
            System.out.println(namm + " " + thangg + " " + ngayy);
            int nammC = Integer.parseInt(nam.format(departDateD));
            int thanggC = Integer.parseInt(thang.format(departDateD));
            int ngayyC = Integer.parseInt(ngay.format(departDateD));

            if (nammC > namm) {
                checkNgaySinh = 0;
            } else if (nammC == namm) {
                if (thanggC > thangg) {
                    checkNgaySinh = 0;
                } else if (thanggC == thangg) {
                    if (ngayyC > ngayy) {
                        checkNgaySinh = 0;
                    }
                }
            }

        } catch (Exception e) {
            checkNgaySinh = 0;
        }

        String nhapLai = tf_nhapLaiMatKhau.getText();
        String queQuan = tf_queQuan.getText();
        String soCMT = tf_soChungMinhThu.getText();
        String soDT = tf_soDienThoai.getText();
        String taiKhoan = tf_taiKhoan.getText();
        int gioiTinh = 0;
        if (rb_Nam.isSelected()) {
            gioiTinh = 1;
        }

        String loai = "";
        if (rb_phongCLC.isSelected()) {
            loai = "CLC";
        } else if (rb_phongCoBan.isSelected()) {
            loai = "CB";
        } else {
            loai = "TC";
        }

        String hocLuc = "";
        if (rb_gioi.isSelected()) {
            hocLuc = "Giỏi";
        } else if (rb_kha.isSelected()) {
            hocLuc = "Khá";
        } else if (rb_tb.isSelected()) {
            hocLuc = "Trung bình";
        } else if (rb_yeu.isSelected()) {
            hocLuc = "Yếu";
        }

        String hanhKiem = "";
        if (rb_hkKha.isSelected()) {
            hanhKiem = "Khá";
        } else if (rb_hkTB.isSelected()) {
            hanhKiem = "Trung bình";
        } else if (rb_hkTot.isSelected()) {
            hanhKiem = "Tốt";
        } else if (rb_hkYeu.isSelected()) {
            hanhKiem = "Yếu";
        }

        if (tf_soThang.getText().equals("") || email.equals("") || hoTen.equals("") || maSV.equals("") || matKhau.equals("")
                || nhapLai.equals("") || queQuan.equals("") || soCMT.equals("") || soDT.equals("") || taiKhoan.equals("")) {
            JOptionPane.showMessageDialog(this, "Cần nhập đủ tất cả thông tin!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (checkNgaySinh == 0) {
            JOptionPane.showMessageDialog(null, "Hãy chọn lại ngày sinh!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if ((!rb_Nam.isSelected()) && (!rb_Nu.isSelected())) {
            JOptionPane.showMessageDialog(this, "Cần chọn giới tính!", "Thông báo", JOptionPane.PLAIN_MESSAGE);
        } else if (!rb_phongCLC.isSelected() && !rb_phongCoBan.isSelected() && !rb_phongTieuChuan.isSelected()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa chọn loại phòng!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (!rb_gioi.isSelected() && !rb_kha.isSelected() && !rb_tb.isSelected() && !rb_yeu.isSelected()) {
            JOptionPane.showMessageDialog(null, "Chưa chọn loại học lực!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (!rb_hkTot.isSelected() && !rb_hkKha.isSelected() && !rb_hkTB.isSelected() && !rb_hkYeu.isSelected()) {
            JOptionPane.showMessageDialog(null, "Chưa chọn loại hạnh kiểm!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else if (!matKhau.equals(nhapLai)) {
            JOptionPane.showMessageDialog(this, "Nhập lại mật khẩu chưa trùng khớp! Mời nhập lại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            tf_nhapLaiMatKhau.setText("");
        } else if (!cb_camKet.isSelected()) {
            JOptionPane.showMessageDialog(this, "Cần chấp nhận nội quy của ký túc xá!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            int x = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn đã điền đúng thông tin đăng ký?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (x == 0) {

                try {
                    ResultSet rs = sv.ShowSinhVienTheoTaiKhoan(taiKhoan);
                    if (rs.next()) {
                        JOptionPane.showMessageDialog(null, "Tài khoản đã có người đăng ký!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    } else {
                        ResultSet rs1 = ph.ShowPhongConTrongTheoLoaiPhong(loai);
                        if (rs1.next()) {

                            ResultSet rs2 = sv.ShowSinhVienTheoMaSV(maSV);
                            if (rs2.next()) {
                                JOptionPane.showMessageDialog(null, "Đã tồn tại mã sinh viên này!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                            } else {

                                ResultSet rs3 = sv.ShowSinhVienTheoSoCMT(soCMT);
                                if (rs3.next()) {
                                    JOptionPane.showMessageDialog(null, "Đã tồn tại số chứng minh thư này!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                                } else {
                                    sv.InsertData(maSV, hoTen, gioiTinh, soCMT, ngaySinh, queQuan,
                                            soDT, email, hocLuc, loai, taiKhoan, matKhau, hanhKiem, 0, 0, thangO);
                                    JOptionPane.showMessageDialog(this, "Đăng ký thành công! Vui lòng chờ điện thoại từ ký túc xá!", "Thông báo", JOptionPane.PLAIN_MESSAGE);
                                    DangNhapScreen a = new DangNhapScreen();
                                    a.setVisible(true);
                                    this.dispose();
                                }
                            }

                        } else {
                            JOptionPane.showMessageDialog(null, "Loại phòng " + loai + " đã hết phòng!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                        }

                    }
                } catch (SQLException ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Đăng ký thất bại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                }

            }
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void rb_NamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_NamActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_rb_NamActionPerformed

    private void rb_NuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_NuActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_rb_NuActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String[] options = {"Phòng tiêu chuẩn", "Phòng cơ bản", "Phòng chất lượng cao"};

        int x = JOptionPane.showOptionDialog(null, "Hãy chọn loại phòng bạn muốn xem!",
                "Thông báo",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
        if (x == 2) {
            //this.dispose();
            LoaiPhongScreen a = new LoaiPhongScreen("PHÒNG CHẤT LƯỢNG CAO 4-6 GIƯỜNG", "<html>Trang thiết bị: Bình nóng lạnh, điều hòa, tủ cá nhân, giường tầng.<br><br> \n"
                    + "Công trình phụ khép kín.<br><br>  \n"
                    + "Giá phòng: <br><br>550.000/SV/tháng  \n",
                    //  + "4 người	&nbsp;&nbsp;&nbsp;&nbsp;	&nbsp;&nbsp;&nbsp;&nbsp;550.000/SV/tháng	&nbsp;&nbsp;&nbsp;&nbsp;450.000/SV/tháng<br> \n"
                    //  + "6 người	&nbsp;&nbsp;&nbsp;&nbsp;367.000/SV/tháng	&nbsp;&nbsp;&nbsp;&nbsp;367.000/SV/tháng	&nbsp;&nbsp;&nbsp;&nbsp;300.000/SV/tháng</html>",
                    "/quanlykitucxa/images/clc1.png", "/quanlykitucxa/images/clc2.png", "/quanlykitucxa/images/clc3.png", "/quanlykitucxa/images/clc4.png");
            a.setVisible(true);
        } else if (x == 1) {
            // this.dispose();
            LoaiPhongScreen a = new LoaiPhongScreen("PHÒNG CƠ BẢN 4-6 GIƯỜNG", "<html>Trang thiết bị: tủ cá nhân, giường tầng.<br><br> \n"
                    + "Công trình phụ khép kín.<br><br>  \n"
                    + "Giá phòng: <br><br>330.000/SV/tháng  \n",
                    // + "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cơ sở 1	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cơ sở 2	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cơ sở 3<br><br>\n"
                    // + "4 người	&nbsp;&nbsp;&nbsp;&nbsp;	&nbsp;&nbsp;&nbsp;&nbsp;300.000/SV/tháng	&nbsp;&nbsp;&nbsp;&nbsp;248.000/SV/tháng<br> \n"
                    // + "6 người	&nbsp;&nbsp;&nbsp;&nbsp;220.000/SV/tháng	&nbsp;&nbsp;&nbsp;&nbsp;200.000/SV/tháng	&nbsp;&nbsp;&nbsp;&nbsp;165.000/SV/tháng</html>",
                    "/quanlykitucxa/images/coBan3.png", "/quanlykitucxa/images/coBan2.png", "/quanlykitucxa/images/coBan1.png", "/quanlykitucxa/images/coBan4.png");
            a.setVisible(true);
        } else if (x == 0) {
            //this.dispose();
            LoaiPhongScreen a = new LoaiPhongScreen("PHÒNG TIÊU CHUẨN 4-6 GIƯỜNG", "<html>Trang thiết bị: Bình nóng lạnh, tủ cá nhân, giường tầng.<br><br> \n"
                    + "Công trình phụ khép kín.<br><br>  \n"
                    + "Giá phòng: <br><br>420.000/SV/tháng  \n",
                    //  + "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cơ sở 1	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cơ sở 2	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Cơ sở 3<br><br>\n"
                    // + "4 người	&nbsp;&nbsp;&nbsp;&nbsp;	&nbsp;&nbsp;&nbsp;&nbsp;375.000/SV/tháng	&nbsp;&nbsp;&nbsp;&nbsp;330.000/SV/tháng<br> \n"
                    // + "6 người	&nbsp;&nbsp;&nbsp;&nbsp;280.000/SV/tháng	&nbsp;&nbsp;&nbsp;&nbsp;250.000/SV/tháng	&nbsp;&nbsp;&nbsp;&nbsp;220.000/SV/tháng</html>",
                    "/quanlykitucxa/images/tc2.png", "/quanlykitucxa/images/tc1.png", "/quanlykitucxa/images/tc4.png", "/quanlykitucxa/images/tc3.png");
            a.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SinhVienDangKyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SinhVienDangKyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SinhVienDangKyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinhVienDangKyScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SinhVienDangKyScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox cb_camKet;
    private org.jdesktop.swingx.JXDatePicker dp_ngaySinh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rb_Nam;
    private javax.swing.JRadioButton rb_Nu;
    private javax.swing.JRadioButton rb_gioi;
    private javax.swing.JRadioButton rb_hkKha;
    private javax.swing.JRadioButton rb_hkTB;
    private javax.swing.JRadioButton rb_hkTot;
    private javax.swing.JRadioButton rb_hkYeu;
    private javax.swing.JRadioButton rb_kha;
    private javax.swing.JRadioButton rb_phongCLC;
    private javax.swing.JRadioButton rb_phongCoBan;
    private javax.swing.JRadioButton rb_phongTieuChuan;
    private javax.swing.JRadioButton rb_tb;
    private javax.swing.JRadioButton rb_yeu;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_hoten;
    private javax.swing.JTextField tf_maSinhVien;
    private javax.swing.JPasswordField tf_matKhau;
    private javax.swing.JPasswordField tf_nhapLaiMatKhau;
    private javax.swing.JTextField tf_queQuan;
    private javax.swing.JTextField tf_soChungMinhThu;
    private javax.swing.JTextField tf_soDienThoai;
    private javax.swing.JTextField tf_soThang;
    private javax.swing.JTextField tf_taiKhoan;
    // End of variables declaration//GEN-END:variables
}
