/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacec;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import process.GiaoTrinh;

/**
 *
 * @author hieuuu
 */
public class GiaoTrinh2 extends javax.swing.JFrame {

    /**
     * Creates new form GiaoTrinh2
     */
    private final GiaoTrinh gt = new GiaoTrinh();
    
    public void showData() throws ClassNotFoundException, SQLException{
        DefaultTableModel tbModel= new DefaultTableModel();
        String colsName[]={"Mã giáo trình","Tên giáo trình","Họ tên tác giả","Số lượng giáo trình","Đơn giá","Ngày xuất bản"};
        tbModel.setColumnIdentifiers(colsName);
        ResultSet rs= gt.ShowGiaoTrinh();
        while(rs.next()){
            String []row= new String[6];
            row[0]=rs.getString("MaGT");
            row[1]=rs.getString("TenGT");
            row[2]=rs.getString("HoTenTG");
            row[3]=rs.getString("Soluong");
            double donGia=0;
            int soTrang=Integer.parseInt(rs.getString("Sotrang"));
            String loai=rs.getString("Loai");
            if(loai.equals("CB"))
                donGia=soTrang*250;
            else donGia=soTrang*400;
            row[4]=donGia+"";
            row[5]=rs.getString("NgayXB");
            tbModel.addRow(row);
            
        }
        tb_data.setModel(tbModel);
    }
    public void showDat() throws SQLException, ClassNotFoundException{
        DefaultTableModel tb= new DefaultTableModel();
        ResultSet rs= gt.ShowGiaoTrinh();
        String colsName[]={"Mã giáo trình","Tên giáo trình","Tên tác giả","Số lượng giáo trình","Đơn giá","Ngày xuất bản"};
        tb.setColumnIdentifiers(colsName);
        while(rs.next()){
            String row[]= new String[6];
            row[0]=rs.getString("MaGT");
            row[1]=rs.getString("TenGT");
            row[2]=rs.getString("HoTenTG");
            row[3]=rs.getString("Soluong");
            double donGia=0;
            int soTrang= Integer.parseInt(rs.getString("Sotrang"));
            String loai=rs.getString("Loai");
            if(loai.equals("CB")) donGia=250*soTrang;
            else donGia=400*soTrang;
            row[4]=donGia+"";
            row[5]=rs.getString("NgayXB");
            tb.addRow(row);   
        }
        tb_data.setModel(tb);
    }
    public GiaoTrinh2() throws ClassNotFoundException, SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        ButtonGroup gr = new ButtonGroup();
        gr.add(rb_CB);
        gr.add(rb_NC);
        showData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rb_CB = new javax.swing.JRadioButton();
        rb_NC = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        tf_maGiaoTrinh = new javax.swing.JTextField();
        tf_tenGiaoTrinh = new javax.swing.JTextField();
        tf_hoTenTG = new javax.swing.JTextField();
        tf_soTrang = new javax.swing.JTextField();
        tf_soLuong = new javax.swing.JTextField();
        tf_ngay = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_data = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã giáo trình:");

        jLabel2.setText("Tên giáo trình:");

        jLabel3.setText("Họ tên tác giả:");

        jLabel4.setText("Số lượng:");

        jLabel5.setText("Số trang:");

        jLabel6.setText("Ngày xuất bản:");

        rb_CB.setText("CB");

        rb_NC.setText("NC");

        jLabel7.setText("Loại:");

        tb_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_data);

        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(51, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_maGiaoTrinh)
                                    .addComponent(tf_tenGiaoTrinh)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(tf_hoTenTG))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_ngay))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_soLuong))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_soTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_NC)
                            .addComponent(rb_CB))
                        .addGap(118, 118, 118))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(rb_CB)
                    .addComponent(jLabel1)
                    .addComponent(tf_maGiaoTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_soTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_NC)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(tf_tenGiaoTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_soLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(tf_hoTenTG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_ngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String maGT = tf_maGiaoTrinh.getText();
        String tenGT = tf_tenGiaoTrinh.getText();
        String hoTenTG = tf_hoTenTG.getText();
        String soLuong = tf_soLuong.getText();
        String soTrang = tf_soTrang.getText();
        String ngayXB = tf_ngay.getText();
        String loai = "";
        if (rb_CB.isSelected()) {
            loai = "CB";
        } else if (rb_NC.isSelected()) {
            loai = "NC";
        }
        if (maGT.equals("") || tenGT.equals("") || hoTenTG.equals("") || soLuong.equals("") || soTrang.equals("") || ngayXB.equals("") || loai.equals("")) {
            JOptionPane.showMessageDialog(null, "Cần nhập đủ tất cả các thông tin!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        } else {
            ResultSet rs;
            try {
                rs = gt.ShowGiaoTrinhTheoMa(maGT);
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Mã giáo trình đã tồn tại!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                } else {
                    try {
                        gt.InSertGiaoTrinh(maGT, tenGT, hoTenTG, soLuong, soTrang, ngayXB, loai);
                        
                        JOptionPane.showMessageDialog(null, "Thêm thành công!", "Thông báo", JOptionPane.PLAIN_MESSAGE);
                        showData();
                    } catch (SQLException ex) {
                       // ex.printStackTrace();
                        JOptionPane.showMessageDialog(null, "Cần nhập ngày xuất bản theo định dạng Năm-Tháng-Ngày!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    } catch (ClassNotFoundException ex) {
                      //  ex.printStackTrace();
                        //JOptionPane.showMessageDialog(null, "Thêm thất bại2!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GiaoTrinh2.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(GiaoTrinh2.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    public void setKhoaTextField(boolean khoa){
        tf_hoTenTG.setEnabled(khoa);
        tf_maGiaoTrinh.setEnabled(khoa);
        tf_ngay.setEnabled(khoa);
        tf_soLuong.setEnabled(khoa);
        tf_soTrang.setEnabled(khoa);
        tf_tenGiaoTrinh.setEnabled(khoa);
        rb_CB.setEnabled(khoa);
        rb_NC.setEnabled(khoa);
    }
    private void tb_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_dataMouseClicked
        // TODO add your handling code here:
        int row= tb_data.getSelectedRow();
        String maGT= (String) tb_data.getModel().getValueAt(row, 0);
        ResultSet rs;
        try {
            rs = gt.ShowGiaoTrinhTheoMa(maGT);
            if(rs.next()){
            tf_hoTenTG.setText(rs.getString("HoTenTG"));
            tf_maGiaoTrinh.setText(rs.getString("MaGT"));
            tf_ngay.setText(rs.getString("NgayXB"));
            tf_soLuong.setText(rs.getString("Soluong"));
            tf_soTrang.setText(rs.getString("Sotrang"));
            if(rs.getString("Loai").equals("CB")) rb_CB.setSelected(true);
            else rb_NC.setSelected(true);
            tf_tenGiaoTrinh.setText(rs.getString("TenGT"));
        }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GiaoTrinh2.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(GiaoTrinh2.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_tb_dataMouseClicked

    /**
     * @param args the command line arguments
     */
    public void ShowData() {

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoTrinh2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoTrinh2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoTrinh2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoTrinh2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GiaoTrinh2().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(GiaoTrinh2.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(GiaoTrinh2.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb_CB;
    private javax.swing.JRadioButton rb_NC;
    private javax.swing.JTable tb_data;
    private javax.swing.JTextField tf_hoTenTG;
    private javax.swing.JTextField tf_maGiaoTrinh;
    private javax.swing.JTextField tf_ngay;
    private javax.swing.JTextField tf_soLuong;
    private javax.swing.JTextField tf_soTrang;
    private javax.swing.JTextField tf_tenGiaoTrinh;
    // End of variables declaration//GEN-END:variables
}
